
/**
 * baseUvt (undefined)=> no aplica
 * baseEnPesos (undefined)=> 100%
 * https://www.abcfinanzas.com/wp-content/uploads/2016/12/Tabla-Retenci%C3%B3n-en-la-fuente-2017.pdf
 * https://www.abcfinanzas.com/finanzas-personales/impuestos/tabla-retencion-la-fuente-ano-2018
 */
var horariosSource= [
    //1001 - Lunes
    {"curso": "1001", "materia": "TRIGO", "hora": "1", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Lunes"},
    {"curso": "1001", "materia": "TRIGO", "hora": "2", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Lunes"},
    {"curso": "1001", "materia": "TECNO", "hora": "3", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Lunes"},
    {"curso": "1001", "materia": "TECNO", "hora": "4", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Lunes"},
    {"curso": "1001", "materia": "RELIG", "hora": "5", "salon": "S_1", "profesor": "Edward Estupiñan", "dia": "Lunes"},
    {"curso": "1001", "materia": "LCRIT", "hora": "6", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Lunes"},
    //1001 - Martes
    {"curso": "1001", "materia": "FIS", "hora": "1", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Martes"},
    {"curso": "1001", "materia": "FIS", "hora": "2", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Martes"},
    {"curso": "1001", "materia": "", "hora": "3", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Martes"},
    {"curso": "1001", "materia": "FILO", "hora": "4", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Martes"},
    {"curso": "1001", "materia": "EDFIS", "hora": "5", "salon": "", "profesor": "Fabio Rozo", "dia": "Martes"},
    {"curso": "1001", "materia": "ARTIS", "hora": "6", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Martes"},
    //1001 - Miercoles
    {"curso": "1001", "materia": "CPE", "hora": "1", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Miercoles"},
    {"curso": "1001", "materia": "CPE", "hora": "2", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Miercoles"},
    {"curso": "1001", "materia": "ING_Conv", "hora": "3", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Miercoles"},
    {"curso": "1001", "materia": "ING_Conv", "hora": "4", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Miercoles"},
    {"curso": "1001", "materia": "SEMIO 1", "hora": "5", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Miercoles"},
    {"curso": "1001", "materia": "SEMIO 1", "hora": "6", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Miercoles"},
    //1001 - Jueves
    {"curso": "1001", "materia": "SEMIO 1", "hora": "1", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Jueves"},
    {"curso": "1001", "materia": "ETICA", "hora": "2", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Jueves"},
    {"curso": "1001", "materia": "ING_Bas", "hora": "3", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Jueves"},
    {"curso": "1001", "materia": "ING_Bas", "hora": "4", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Jueves"},
    {"curso": "1001", "materia": "QUIM", "hora": "5", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Jueves"},
    {"curso": "1001", "materia": "QUIM", "hora": "6", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Jueves"},
    //1001 - Viernes
    {"curso": "1001", "materia": "QUIM", "hora": "1", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Viernes"},
    {"curso": "1001", "materia": "EDFIS", "hora": "2", "salon": "", "profesor": "Fabio Rozo", "dia": "Viernes"},
    {"curso": "1001", "materia": "ING_Bas", "hora": "3", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Viernes"},
    {"curso": "1001", "materia": "ING_Bas", "hora": "4", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Viernes"},
    {"curso": "1001", "materia": "LCAS", "hora": "5", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Viernes"},
    {"curso": "1001", "materia": "LCAS", "hora": "6", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Viernes"},
    //1002 - Lunes
    {"curso": "1002", "materia": "ING_Bas", "hora": "1", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Lunes"},
    {"curso": "1002", "materia": "ING_Bas", "hora": "2", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Lunes"},
    {"curso": "1002", "materia": "ARTIS", "hora": "3", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Lunes"},
    {"curso": "1002", "materia": "QUIM", "hora": "4", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Lunes"},
    {"curso": "1002", "materia": "FILO", "hora": "5", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Lunes"},
    {"curso": "1002", "materia": "FILO", "hora": "6", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Lunes"},
    //1002 - Martes
    {"curso": "1002", "materia": "EDFIS", "hora": "1", "salon": "", "profesor": "Fabio Rozo", "dia": "Martes"},
    {"curso": "1002", "materia": "SEMIO 1", "hora": "2", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Martes"},
    {"curso": "1002", "materia": "TRIGO", "hora": "3", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Martes"},
    {"curso": "1002", "materia": "TRIGO", "hora": "4", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Martes"},
    {"curso": "1002", "materia": "ING_Conv", "hora": "5", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Martes"},
    {"curso": "1002", "materia": "ING_Conv", "hora": "6", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Martes"},
    //1002 - Miercoles
    {"curso": "1002", "materia": "FIS", "hora": "1", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Miercoles"},
    {"curso": "1002", "materia": "FIS", "hora": "2", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Miercoles"},
    {"curso": "1002", "materia": "QUIM", "hora": "3", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Miercoles"},
    {"curso": "1002", "materia": "QUIM", "hora": "4", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Miercoles"},
    {"curso": "1002", "materia": "LCAS", "hora": "5", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Miercoles"},
    {"curso": "1002", "materia": "LCAS", "hora": "6", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Miercoles"},
    //1002 - Jueves
    {"curso": "1002", "materia": "ETICA", "hora": "1", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Jueves"},
    {"curso": "1002", "materia": "RELIG", "hora": "2", "salon": "S_16", "profesor": "Edward Estupiñan", "dia": "Jueves"},
    {"curso": "1002", "materia": "EDFIS", "hora": "3", "salon": "", "profesor": "Fabio Rozo", "dia": "Jueves"},
    {"curso": "1002", "materia": "LCRIT", "hora": "4", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Jueves"},
    {"curso": "1002", "materia": "CPE", "hora": "5", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Jueves"},
    {"curso": "1002", "materia": "CPE", "hora": "6", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Jueves"},
    //1002 - Viernes
    {"curso": "1002", "materia": "ING_Bas", "hora": "1", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Viernes"},
    {"curso": "1002", "materia": "ING_Bas", "hora": "2", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Viernes"},
    {"curso": "1002", "materia": "TECNO", "hora": "3", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Viernes"},
    {"curso": "1002", "materia": "TECNO", "hora": "4", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Viernes"},
    {"curso": "1002", "materia": "SEMIO 1", "hora": "5", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Viernes"},
    {"curso": "1002", "materia": "SEMIO 1", "hora": "6", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Viernes"},
    //1003 - Lunes
    {"curso": "1003", "materia": "QUIM", "hora": "1", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Lunes"},
    {"curso": "1003", "materia": "QUIM", "hora": "2", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Lunes"},
    {"curso": "1003", "materia": "LCAS", "hora": "3", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Lunes"},
    {"curso": "1003", "materia": "LCAS", "hora": "4", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Lunes"},
    {"curso": "1003", "materia": "ING_Bas", "hora": "5", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Lunes"},
    {"curso": "1003", "materia": "ING_Bas", "hora": "6", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Lunes"},
    //1003 - Martes
    {"curso": "1003", "materia": "TECNO", "hora": "1", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Martes"},
    {"curso": "1003", "materia": "TECNO", "hora": "2", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Martes"},
    {"curso": "1003", "materia": "ING_Bas", "hora": "3", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Martes"},
    {"curso": "1003", "materia": "ING_Bas", "hora": "4", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Martes"},
    {"curso": "1003", "materia": "FIS", "hora": "5", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Martes"},
    {"curso": "1003", "materia": "FIS", "hora": "6", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Martes"},
    //1003 - Miercoles
    {"curso": "1003", "materia": "COMP_M", "hora": "1", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Miercoles"},
    {"curso": "1003", "materia": "QUIM", "hora": "2", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Miercoles"},
    {"curso": "1003", "materia": "ARTIS", "hora": "3", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Miercoles"},
    {"curso": "1003", "materia": "ETICA", "hora": "4", "salon": "S_7", "profesor": "Nancy Combariza", "dia": "Miercoles"},
    {"curso": "1003", "materia": "TRIGO", "hora": "5", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Miercoles"},
    {"curso": "1003", "materia": "TRIGO", "hora": "6", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Miercoles"},
    //1003 - Jueves
    {"curso": "1003", "materia": "FILO", "hora": "1", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Jueves"},
    {"curso": "1003", "materia": "FILO", "hora": "2", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Jueves"},
    {"curso": "1003", "materia": "COMP_M", "hora": "3", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Jueves"},
    {"curso": "1003", "materia": "COMP_M", "hora": "4", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Jueves"},
    {"curso": "1003", "materia": "LCRIT", "hora": "5", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Jueves"},
    {"curso": "1003", "materia": "EDFIS", "hora": "6", "salon": "", "profesor": "Fabio Rozo", "dia": "Jueves"},
    //1003 - Viernes
    {"curso": "1003", "materia": "EDFIS", "hora": "1", "salon": "", "profesor": "Fabio Rozo", "dia": "Viernes"},
    {"curso": "1003", "materia": "RELIG", "hora": "2", "salon": "S_16", "profesor": "Edward Estupiñan", "dia": "Viernes"},
    {"curso": "1003", "materia": "ESTADIS", "hora": "3", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Viernes"},
    {"curso": "1003", "materia": "ESTADIS", "hora": "4", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Viernes"},
    {"curso": "1003", "materia": "CPE", "hora": "5", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Viernes"},
    {"curso": "1003", "materia": "CPE", "hora": "6", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Viernes"},
    //1004 - Lunes
    {"curso": "1004", "materia": "QUIM", "hora": "1", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Lunes"},
    {"curso": "1004", "materia": "QUIM", "hora": "2", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Lunes"},
    {"curso": "1004", "materia": "ING_Bas", "hora": "3", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Lunes"},
    {"curso": "1004", "materia": "ING_Bas", "hora": "4", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Lunes"},
    {"curso": "1004", "materia": "ARTIS", "hora": "5", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Lunes"},
    {"curso": "1004", "materia": "COMP_M", "hora": "6", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Lunes"},
    //1004 - Martes
    {"curso": "1004", "materia": "ESTADIS", "hora": "1", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Martes"},
    {"curso": "1004", "materia": "ESTADIS", "hora": "2", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Martes"},
    {"curso": "1004", "materia": "EDFIS", "hora": "3", "salon": "", "profesor": "Fabio Rozo", "dia": "Martes"},
    {"curso": "1004", "materia": "LCRIT", "hora": "4", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Martes"},
    {"curso": "1004", "materia": "CPE", "hora": "5", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Martes"},
    {"curso": "1004", "materia": "CPE", "hora": "6", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Martes"},
    //1004 - Miercoles
    {"curso": "1004", "materia": "TECNO", "hora": "1", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Miercoles"},
    {"curso": "1004", "materia": "TECNO", "hora": "2", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Miercoles"},
    {"curso": "1004", "materia": "COMP_M", "hora": "3", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Miercoles"},
    {"curso": "1004", "materia": "COMP_M", "hora": "4", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Miercoles"},
    {"curso": "1004", "materia": "ING_Bas", "hora": "5", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Miercoles"},
    {"curso": "1004", "materia": "ING_Bas", "hora": "6", "salon": "S_18", "profesor": "18-Diana Vera", "dia": "Miercoles"},
    //1004 - Jueves
    {"curso": "1004", "materia": "EDFIS", "hora": "1", "salon": "", "profesor": "Fabio Rozo", "dia": "Jueves"},
    {"curso": "1004", "materia": "LCAS", "hora": "2", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Jueves"},
    {"curso": "1004", "materia": "LCAS", "hora": "3", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Jueves"},
    {"curso": "1004", "materia": "QUIM", "hora": "4", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Jueves"},
    {"curso": "1004", "materia": "ETICA", "hora": "5", "salon": "S_7", "profesor": "Nancy Combariza", "dia": "Jueves"},
    {"curso": "1004", "materia": "RELIG", "hora": "6", "salon": "S_16", "profesor": "Edward Estupiñan", "dia": "Jueves"},
    //1004 - Viernes
    {"curso": "1004", "materia": "FILO", "hora": "1", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Viernes"},
    {"curso": "1004", "materia": "FILO", "hora": "2", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Viernes"},
    {"curso": "1004", "materia": "FIS", "hora": "3", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Viernes"},
    {"curso": "1004", "materia": "FIS", "hora": "4", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Viernes"},
    {"curso": "1004", "materia": "TRIGO", "hora": "5", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Viernes"},
    {"curso": "1004", "materia": "TRIGO", "hora": "6", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Viernes"},
    //1005 - Lunes
    {"curso": "1005", "materia": "ING_Bas", "hora": "1", "salon": "S_20", "profesor": "Alba N Salamanca", "dia": "Lunes"},
    {"curso": "1005", "materia": "ING_Bas", "hora": "2", "salon": "S_20", "profesor": "Alba N Salamanca", "dia": "Lunes"},
    {"curso": "1005", "materia": "QUIM", "hora": "3", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Lunes"},
    {"curso": "1005", "materia": "EDFIS", "hora": "4", "salon": "", "profesor": "Fabio Rozo", "dia": "Lunes"},
    {"curso": "1005", "materia": "CPE", "hora": "5", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Lunes"},
    {"curso": "1005", "materia": "CPE", "hora": "6", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Lunes"},
    //1005 - Martes
    {"curso": "1005", "materia": "QUIM", "hora": "1", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Martes"},
    {"curso": "1005", "materia": "QUIM", "hora": "2", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Martes"},
    {"curso": "1005", "materia": "TRIGO", "hora": "3", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Martes"},
    {"curso": "1005", "materia": "TRIGO", "hora": "4", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Martes"},
    {"curso": "1005", "materia": "LCAS", "hora": "5", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Martes"},
    {"curso": "1005", "materia": "LCAS", "hora": "6", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Martes"},
    //1005 - Miercoles
    {"curso": "1005", "materia": "ANALI", "hora": "1", "salon": "S_15", "profesor": "15-Yolima Alfaro", "dia": "Miercoles"},
    {"curso": "1005", "materia": "LCRIT", "hora": "2", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Miercoles"},
    {"curso": "1005", "materia": "RELIG", "hora": "3", "salon": "S_12", "profesor": "Edward Estupiñan", "dia": "Miercoles"},
    {"curso": "1005", "materia": "TECNO", "hora": "4", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Miercoles"},
    {"curso": "1005", "materia": "TECNO", "hora": "5", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Miercoles"},
    {"curso": "1005", "materia": "EDFIS", "hora": "6", "salon": "", "profesor": "Fabio Rozo", "dia": "Miercoles"},
    //1005 - Jueves
    {"curso": "1005", "materia": "ING_Bas", "hora": "1", "salon": "S_19", "profesor": "Alba N Salamanca", "dia": "Jueves"},
    {"curso": "1005", "materia": "ING_Bas", "hora": "2", "salon": "S_19", "profesor": "Alba N Salamanca", "dia": "Jueves"},
    {"curso": "1005", "materia": "FIS", "hora": "3", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Jueves"},
    {"curso": "1005", "materia": "FIS", "hora": "4", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Jueves"},
    {"curso": "1005", "materia": "Bio_CEL", "hora": "5", "salon": "S_16", "profesor": "16-William Pita", "dia": "Jueves"},
    {"curso": "1005", "materia": "Bio_CEL", "hora": "6", "salon": "S_16", "profesor": "16-William Pita", "dia": "Jueves"},
    //1005 - Viernes
    {"curso": "1005", "materia": "ETICA", "hora": "1", "salon": "S_21", "profesor": "Alba N Salamanca", "dia": "Viernes"},
    {"curso": "1005", "materia": "ARTIS", "hora": "2", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Viernes"},
    {"curso": "1005", "materia": "ANALI", "hora": "3", "salon": "S_15", "profesor": "15-Yolima Alfaro", "dia": "Viernes"},
    {"curso": "1005", "materia": "ANALI", "hora": "4", "salon": "S_15", "profesor": "15-Yolima Alfaro", "dia": "Viernes"},
    {"curso": "1005", "materia": "FILO", "hora": "5", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Viernes"},
    {"curso": "1005", "materia": "FILO", "hora": "6", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Viernes"},
    //1006 - Lunes
    {"curso": "1006", "materia": "ARTIS", "hora": "1", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Lunes"},
    {"curso": "1006", "materia": "LCRIT", "hora": "2", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Lunes"},
    {"curso": "1006", "materia": "FILO", "hora": "3", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Lunes"},
    {"curso": "1006", "materia": "FILO", "hora": "4", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Lunes"},
    {"curso": "1006", "materia": "ING_Bas", "hora": "5", "salon": "S_21", "profesor": "Alba N Salamanca", "dia": "Lunes"},
    {"curso": "1006", "materia": "ING_Bas", "hora": "6", "salon": "S_21", "profesor": "Alba N Salamanca", "dia": "Lunes"},
    //1006 - Martes
    {"curso": "1006", "materia": "ANALI", "hora": "1", "salon": "S_15", "profesor": "15-Yolima Alfaro", "dia": "Martes"},
    {"curso": "1006", "materia": "ANALI", "hora": "2", "salon": "S_15", "profesor": "15-Yolima Alfaro", "dia": "Martes"},
    {"curso": "1006", "materia": "QUIM", "hora": "3", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Martes"},
    {"curso": "1006", "materia": "EDFIS", "hora": "4", "salon": "", "profesor": "Fabio Rozo", "dia": "Martes"},
    {"curso": "1006", "materia": "Bio_CEL", "hora": "5", "salon": "S_16", "profesor": "16-William Pita", "dia": "Martes"},
    {"curso": "1006", "materia": "Bio_CEL", "hora": "6", "salon": "S_16", "profesor": "16-William Pita", "dia": "Martes"},
    //1006 - Miercoles
    {"curso": "1006", "materia": "TRIGO", "hora": "1", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Miercoles"},
    {"curso": "1006", "materia": "TRIGO", "hora": "2", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Miercoles"},
    {"curso": "1006", "materia": "LCAS", "hora": "3", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Miercoles"},
    {"curso": "1006", "materia": "LCAS", "hora": "4", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Miercoles"},
    {"curso": "1006", "materia": "QUIM", "hora": "5", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Miercoles"},
    {"curso": "1006", "materia": "QUIM", "hora": "6", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Miercoles"},
    //1006 - Jueves
    {"curso": "1006", "materia": "CPE", "hora": "1", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Jueves"},
    {"curso": "1006", "materia": "CPE", "hora": "2", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Jueves"},
    {"curso": "1006", "materia": "ING_Bas", "hora": "3", "salon": "S_20", "profesor": "Alba N Salamanca", "dia": "Jueves"},
    {"curso": "1006", "materia": "ING_Bas", "hora": "4", "salon": "S_20", "profesor": "Alba N Salamanca", "dia": "Jueves"},
    {"curso": "1006", "materia": "TECNO", "hora": "5", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Jueves"},
    {"curso": "1006", "materia": "TECNO", "hora": "6", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Jueves"},
    //1006 - Viernes
    {"curso": "1006", "materia": "FIS", "hora": "1", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Viernes"},
    {"curso": "1006", "materia": "FIS", "hora": "2", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Viernes"},
    {"curso": "1006", "materia": "RELIG", "hora": "3", "salon": "S_12", "profesor": "Edward Estupiñan", "dia": "Viernes"},
    {"curso": "1006", "materia": "EDFIS", "hora": "4", "salon": "", "profesor": "Fabio Rozo", "dia": "Viernes"},
    {"curso": "1006", "materia": "ETICA", "hora": "5", "salon": "SALA_15", "profesor": "15-Yolima Alfaro", "dia": "Viernes"},
    {"curso": "1006", "materia": "ANALI", "hora": "6", "salon": "SALA_15", "profesor": "15-Yolima Alfaro", "dia": "Viernes"},
    //1007 - Lunes
    {"curso": "1007", "materia": "LCRIT", "hora": "1", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Lunes"},
    {"curso": "1007", "materia": "EDFIS", "hora": "2", "salon": "", "profesor": "Angela Morales", "dia": "Lunes"},
    {"curso": "1007", "materia": "ING_Bas", "hora": "3", "salon": "S_19", "profesor": "Alba N Salamanca", "dia": "Lunes"},
    {"curso": "1007", "materia": "ING_Bas", "hora": "4", "salon": "S_19", "profesor": "Alba N Salamanca", "dia": "Lunes"},
    {"curso": "1007", "materia": "TRIGO", "hora": "5", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Lunes"},
    {"curso": "1007", "materia": "CPE", "hora": "6", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Lunes"},
    //1007 - Martes
    {"curso": "1007", "materia": "FILO", "hora": "1", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Martes"},
    {"curso": "1007", "materia": "FILO", "hora": "2", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Martes"},
    {"curso": "1007", "materia": "TECNO", "hora": "3", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Martes"},
    {"curso": "1007", "materia": "TECNO", "hora": "4", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Martes"},
    {"curso": "1007", "materia": "LCAS", "hora": "5", "salon": "S_10", "profesor": "Esperanza Orozco", "dia": "Martes"},
    {"curso": "1007", "materia": "QUIM", "hora": "6", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Martes"},
    //1007 - Miercoles
    {"curso": "1007", "materia": "ETICA", "hora": "1", "salon": "S_1", "profesor": "Nancy Cobariza", "dia": "Miercoles"},
    {"curso": "1007", "materia": "FIS", "hora": "2", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Miercoles"},
    {"curso": "1007", "materia": "FIS", "hora": "3", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Miercoles"},
    {"curso": "1007", "materia": "CPE", "hora": "4", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Miercoles"},
    {"curso": "1007", "materia": "CPE", "hora": "5", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Miercoles"},
    {"curso": "1007", "materia": "RELIG", "hora": "6", "salon": "S_16", "profesor": "Edward Estupiñan", "dia": "Miercoles"},
    //1007 - Jueves
    {"curso": "1007", "materia": "EDFIS", "hora": "1", "salon": "", "profesor": "Angela Morales", "dia": "Jueves"},
    {"curso": "1007", "materia": "LCAS", "hora": "2", "salon": "S_10", "profesor": "Esperanza Orozco", "dia": "Jueves"},
    {"curso": "1007", "materia": "LCAS", "hora": "3", "salon": "S_10", "profesor": "Esperanza Orozco", "dia": "Jueves"},
    {"curso": "1007", "materia": "ARTIS", "hora": "4", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Jueves"},
    {"curso": "1007", "materia": "APLIC 1", "hora": "5", "salon": "SALA_6", "profesor": "S5-Rosa Guerrero", "dia": "Jueves"},
    {"curso": "1007", "materia": "APLIC 1", "hora": "6", "salon": "SALA_6", "profesor": "S5-Rosa Guerrero", "dia": "Jueves"},
    //1007 - Viernes
    {"curso": "1007", "materia": "QUIM", "hora": "1", "salon": "s_11", "profesor": "11-Lilia Montoya", "dia": "Viernes"},
    {"curso": "1007", "materia": "QUIM", "hora": "2", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Viernes"},
    {"curso": "1007", "materia": "ING_Bas", "hora": "3", "salon": "S_20", "profesor": "Alba N Salamanca", "dia": "Viernes"},
    {"curso": "1007", "materia": "ING_Bas", "hora": "4", "salon": "S_20", "profesor": "Alba N Salamanca", "dia": "Viernes"},
    {"curso": "1007", "materia": "TRIGO", "hora": "5", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Viernes"},
    {"curso": "1007", "materia": "TRIGO", "hora": "6", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Viernes"},
    //1008 - Lunes
    {"curso": "1008", "materia": "TRIGO", "hora": "1", "salon": "s_4", "profesor": "04-Soraya Fonseca", "dia": "Lunes"},
    {"curso": "1008", "materia": "LCRIT", "hora": "2", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Lunes"},
    {"curso": "1008", "materia": "LCAS", "hora": "3", "salon": "S_3", "profesor": "Esperanza Orozco", "dia": "Lunes"},
    {"curso": "1008", "materia": "LCAS", "hora": "4", "salon": "S_3", "profesor": "Esperanza Orozco", "dia": "Lunes"},
    {"curso": "1008", "materia": "CPE", "hora": "5", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Lunes"},
    {"curso": "1008", "materia": "ARTIS", "hora": "6", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Lunes"},
    //1008 - Martes
    {"curso": "1008", "materia": "EDFIS", "hora": "1", "salon": "", "profesor": "Angela Morales", "dia": "Martes"},
    {"curso": "1008", "materia": "RELIG", "hora": "2", "salon": "S_12", "profesor": "Edward Estupiñan", "dia": "Martes"},
    {"curso": "1008", "materia": "FILO", "hora": "3", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Martes"},
    {"curso": "1008", "materia": "FILO", "hora": "4", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Martes"},
    {"curso": "1008", "materia": "FIS", "hora": "5", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Martes"},
    {"curso": "1008", "materia": "FIS", "hora": "6", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Martes"},
    //1008 - Miercoles
    {"curso": "1008", "materia": "TECNO", "hora": "1", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Miercoles"},
    {"curso": "1008", "materia": "TECNO", "hora": "2", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Miercoles"},
    {"curso": "1008", "materia": "TRIGO", "hora": "3", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Miercoles"},
    {"curso": "1008", "materia": "TRIGO", "hora": "4", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Miercoles"},
    {"curso": "1008", "materia": "ING_Bas", "hora": "5", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Miercoles"},
    {"curso": "1008", "materia": "ING_Bas", "hora": "6", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Miercoles"},
    //1008 - Jueves
    {"curso": "1008", "materia": "QUIM", "hora": "1", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Jueves"},
    {"curso": "1008", "materia": "EDFIS", "hora": "2", "salon": "", "profesor": "Angela Morales", "dia": "Jueves"},
    {"curso": "1008", "materia": "ETICA", "hora": "3", "salon": "S_8", "profesor": "Nancy Cobariza", "dia": "Jueves"},
    {"curso": "1008", "materia": "LCAS", "hora": "4", "salon": "S_3", "profesor": "Esperanza Orozco", "dia": "Jueves"},
    {"curso": "1008", "materia": "CPE", "hora": "5", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Jueves"},
    {"curso": "1008", "materia": "CPE", "hora": "6", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Jueves"},
    //1008 - Viernes
    {"curso": "1008", "materia": "ING_Bas", "hora": "1", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Viernes"},
    {"curso": "1008", "materia": "ING_Bas", "hora": "2", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Viernes"},
    {"curso": "1008", "materia": "APLIC 1", "hora": "3", "salon": "SALA_6", "profesor": "S5-Rosa Guerrero", "dia": "Viernes"},
    {"curso": "1008", "materia": "APLIC 1", "hora": "4", "salon": "SALA_6", "profesor": "S5-Rosa Guerrero", "dia": "Viernes"},
    {"curso": "1008", "materia": "QUIM", "hora": "5", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Viernes"},
    {"curso": "1008", "materia": "QUIM", "hora": "6", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Viernes"},
    //1009 - Lunes
    {"curso": "1009", "materia": "CPE", "hora": "1", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Lunes"},
    {"curso": "1009", "materia": "TRIGO", "hora": "2", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Lunes"},
    {"curso": "1009", "materia": "FIS", "hora": "3", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Lunes"},
    {"curso": "1009", "materia": "FIS", "hora": "4", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Lunes"},
    {"curso": "1009", "materia": "ING_Bas", "hora": "5", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Lunes"},
    {"curso": "1009", "materia": "ING_Bas", "hora": "6", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Lunes"},
    //1009 - Martes
    {"curso": "1009", "materia": "LCAS", "hora": "1", "salon": "S_3", "profesor": "Esperanza Orozco", "dia": "Martes"},
    {"curso": "1009", "materia": "LCAS", "hora": "2", "salon": "S_3", "profesor": "Esperanza Orozco", "dia": "Martes"},
    {"curso": "1009", "materia": "EDFIS", "hora": "3", "salon": "", "profesor": "Angela Morales", "dia": "Martes"},
    {"curso": "1009", "materia": "LCRIT", "hora": "4", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Martes"},
    {"curso": "1009", "materia": "ING_Bas", "hora": "5", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Martes"},
    {"curso": "1009", "materia": "ING_Bas", "hora": "6", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Martes"},
    //1009 - Miercoles
    {"curso": "1009", "materia": "CPE", "hora": "1", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Miercoles"},
    {"curso": "1009", "materia": "CPE", "hora": "2", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Miercoles"},
    {"curso": "1009", "materia": "TECNO", "hora": "3", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Miercoles"},
    {"curso": "1009", "materia": "TECNO", "hora": "4", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Miercoles"},
    {"curso": "1009", "materia": "RELIG", "hora": "5", "salon": "S_16", "profesor": "Edward Estupiñan", "dia": "Miercoles"},
    {"curso": "1009", "materia": "ETICA", "hora": "6", "salon": "S_1", "profesor": "Nancy Cobariza", "dia": "Miercoles"},
    //1009 - Jueves
    {"curso": "1009", "materia": "ARTIS", "hora": "1", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Jueves"},
    {"curso": "1009", "materia": "QUIM", "hora": "2", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Jueves"},
    {"curso": "1009", "materia": "FILO", "hora": "3", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Jueves"},
    {"curso": "1009", "materia": "FILO", "hora": "4", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Jueves"},
    {"curso": "1009", "materia": "LCAS", "hora": "5", "salon": "S_3", "profesor": "Esperanza Orozco", "dia": "Jueves"},
    {"curso": "1009", "materia": "EDFIS", "hora": "6", "salon": "", "profesor": "Angela Morales", "dia": "Jueves"},
    //1009 - Viernes
    {"curso": "1009", "materia": "TRIGO", "hora": "1", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Viernes"},
    {"curso": "1009", "materia": "TRIGO", "hora": "2", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Viernes"},
    {"curso": "1009", "materia": "QUIM", "hora": "3", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Viernes"},
    {"curso": "1009", "materia": "QUIM", "hora": "4", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Viernes"},
    {"curso": "1009", "materia": "APLIC 1", "hora": "5", "salon": "SALA_6", "profesor": "S5-Rosa Guerrero", "dia": "Viernes"},
    {"curso": "1009", "materia": "APLIC 1", "hora": "6", "salon": "SALA_6", "profesor": "S5-Rosa Guerrero", "dia": "Viernes"},
    //1010 - Lunes
    {"curso": "1010", "materia": "QUIM", "hora": "1", "salon": "S_16", "profesor": "16-William Pita", "dia": "Lunes"},
    {"curso": "1010", "materia": "ING_Bas", "hora": "2", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Lunes"},
    {"curso": "1010", "materia": "ING_Bas", "hora": "3", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Lunes"},
    {"curso": "1010", "materia": "RELIG", "hora": "4", "salon": "S_13", "profesor": "Edward Estupiñan", "dia": "Lunes"},
    {"curso": "1010", "materia": "EDFIS", "hora": "5", "salon": "", "profesor": "Angela Morales", "dia": "Lunes"},
    {"curso": "1010", "materia": "CPE", "hora": "6", "salon": "S_11", "profesor": "Ciro Millán", "dia": "Lunes"},
    //1010 - Martes
    {"curso": "1010", "materia": "ETICA", "hora": "1", "salon": "S_1", "profesor": "01-Pedro Contreras", "dia": "Martes"},
    {"curso": "1010", "materia": "TRIGO", "hora": "2", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Martes"},
    {"curso": "1010", "materia": "FINANZAS", "hora": "3", "salon": "S_1", "profesor": "01-Pedro Contreras", "dia": "Martes"},
    {"curso": "1010", "materia": "FINANZAS", "hora": "4", "salon": "S_1", "profesor": "01-Pedro Contreras", "dia": "Martes"},
    {"curso": "1010", "materia": "LCAS", "hora": "5", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Martes"},
    {"curso": "1010", "materia": "LCAS", "hora": "6", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Martes"},
    //1010 - Miercoles
    {"curso": "1010", "materia": "LCRIT", "hora": "1", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Miercoles"},
    {"curso": "1010", "materia": "CPE", "hora": "2", "salon": "S_11", "profesor": "Ciro Millán", "dia": "Miercoles"},
    {"curso": "1010", "materia": "CPE", "hora": "3", "salon": "S_11", "profesor": "Ciro Millán", "dia": "Miercoles"},
    {"curso": "1010", "materia": "EDFIS", "hora": "4", "salon": "", "profesor": "Angela Morales", "dia": "Miercoles"},
    {"curso": "1010", "materia": "FILO", "hora": "5", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Miercoles"},
    {"curso": "1010", "materia": "FILO", "hora": "6", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Miercoles"},
    //1010 - Jueves
    {"curso": "1010", "materia": "ING_Bas", "hora": "1", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Jueves"},
    {"curso": "1010", "materia": "ING_Bas", "hora": "2", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Jueves"},
    {"curso": "1010", "materia": "QUIM", "hora": "3", "salon": "S_16", "profesor": "16-William Pita", "dia": "Jueves"},
    {"curso": "1010", "materia": "QUIM", "hora": "4", "salon": "S_16", "profesor": "16-William Pita", "dia": "Jueves"},
    {"curso": "1010", "materia": "TECNO", "hora": "5", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Jueves"},
    {"curso": "1010", "materia": "TECNO", "hora": "6", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Jueves"},
    //1010 - Viernes
    {"curso": "1010", "materia": "ARTIS", "hora": "1", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Viernes"},
    {"curso": "1010", "materia": "LCAS", "hora": "2", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Viernes"},
    {"curso": "1010", "materia": "TRIGO", "hora": "3", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Viernes"},
    {"curso": "1010", "materia": "TRIGO", "hora": "4", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Viernes"},
    {"curso": "1010", "materia": "FIS", "hora": "5", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Viernes"},
    {"curso": "1010", "materia": "FIS", "hora": "6", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Viernes"},
    //1011 - Lunes
    {"curso": "1011", "materia": "FIS", "hora": "1", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Lunes"},
    {"curso": "1011", "materia": "FIS", "hora": "2", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Lunes"},
    {"curso": "1011", "materia": "RELIG", "hora": "3", "salon": "S_16", "profesor": "Edward Estupiñan", "dia": "Lunes"},
    {"curso": "1011", "materia": "CPE", "hora": "4", "salon": "S_11", "profesor": "Ciro Millán", "dia": "Lunes"},
    {"curso": "1011", "materia": "CPE", "hora": "5", "salon": "S_11", "profesor": "Ciro Millán", "dia": "Lunes"},
    {"curso": "1011", "materia": "TRIGO", "hora": "6", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Lunes"},
    //1011 - Martes
    {"curso": "1011", "materia": "QUIM", "hora": "1", "salon": "S_16", "profesor": "16-William Pita", "dia": "Martes"},
    {"curso": "1011", "materia": "QUIM", "hora": "2", "salon": "S_16", "profesor": "16-William Pita", "dia": "Martes"},
    {"curso": "1011", "materia": "ING_Bas", "hora": "3", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Martes"},
    {"curso": "1011", "materia": "ING_Bas", "hora": "4", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Martes"},
    {"curso": "1011", "materia": "ARTIS", "hora": "5", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Martes"},
    {"curso": "1011", "materia": "EDFIS", "hora": "6", "salon": "", "profesor": "Angela Morales", "dia": "Martes"},
    //1011 - Miercoles
    {"curso": "1011", "materia": "CPE", "hora": "1", "salon": "S_11", "profesor": "Ciro Millán", "dia": "Miercoles"},
    {"curso": "1011", "materia": "LCAS", "hora": "2", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Miercoles"},
    {"curso": "1011", "materia": "LCAS", "hora": "3", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Miercoles"},
    {"curso": "1011", "materia": "LCRIT", "hora": "4", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Miercoles"},
    {"curso": "1011", "materia": "TRIGO", "hora": "5", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Miercoles"},
    {"curso": "1011", "materia": "TRIGO", "hora": "6", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Miercoles"},
    //1011 - Jueves
    {"curso": "1011", "materia": "FINANZAS", "hora": "1", "salon": "SALA_6", "profesor": "S6-Katherine Sepúlveda", "dia": "Jueves"},
    {"curso": "1011", "materia": "FINANZAS", "hora": "2", "salon": "SALA_6", "profesor": "S6-Katherine Sepúlveda", "dia": "Jueves"},
    {"curso": "1011", "materia": "LCAS", "hora": "3", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Jueves"},
    {"curso": "1011", "materia": "EDFIS", "hora": "4", "salon": "", "profesor": "Angela Morales", "dia": "Jueves"},
    {"curso": "1011", "materia": "ING_Bas", "hora": "5", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Jueves"},
    {"curso": "1011", "materia": "ING_Bas", "hora": "6", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Jueves"},
    //1011 - Viernes
    {"curso": "1011", "materia": "FILO", "hora": "1", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Viernes"},
    {"curso": "1011", "materia": "FILO", "hora": "2", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Viernes"},
    {"curso": "1011", "materia": "QUIM", "hora": "3", "salon": "S_16", "profesor": "16-William Pita", "dia": "Viernes"},
    {"curso": "1011", "materia": "ETICA", "hora": "4", "salon": "S_1", "profesor": "01-Pedro Contreras", "dia": "Viernes"},
    {"curso": "1011", "materia": "TECNO", "hora": "5", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Viernes"},
    {"curso": "1011", "materia": "TECNO", "hora": "6", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Viernes"},


    //1101 - Lunes
    {"curso": "1101", "materia": "ING_Bas", "hora": "1", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Lunes"},
    {"curso": "1101", "materia": "ING_Bas", "hora": "2", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Lunes"},
    {"curso": "1101", "materia": "EDFIS", "hora": "3", "salon": "", "profesor": "Fabio Rozo", "dia": "Lunes"},
    {"curso": "1101", "materia": "QUIM", "hora": "4", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Lunes"},
    {"curso": "1101", "materia": "CALCULO", "hora": "5", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Lunes"},
    {"curso": "1101", "materia": "CALCULO", "hora": "6", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Lunes"},
    //1101 - Martes
    {"curso": "1101", "materia": "LCAS", "hora": "1", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Martes"},
    {"curso": "1101", "materia": "LCAS", "hora": "2", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Martes"},
    {"curso": "1101", "materia": "CPE", "hora": "3", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Martes"},
    {"curso": "1101", "materia": "CPE", "hora": "4", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Martes"},
    {"curso": "1101", "materia": "LO_MAT", "hora": "5", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Martes"},
    {"curso": "1101", "materia": "SEMIO 2", "hora": "6", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Martes"},
    //1101 - Miercoles
    {"curso": "1101", "materia": "ING_Conv", "hora": "1", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Miercoles"},
    {"curso": "1101", "materia": "ING_Conv", "hora": "2", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Miercoles"},
    {"curso": "1101", "materia": "EDFIS", "hora": "3", "salon": "", "profesor": "Fabio Rozo", "dia": "Miercoles"},
    {"curso": "1101", "materia": "RELIG", "hora": "4", "salon": "S_11", "profesor": "Edward Estupiñan", "dia": "Miercoles"},
    {"curso": "1101", "materia": "ING_Bas", "hora": "5", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Miercoles"},
    {"curso": "1101", "materia": "ING_Bas", "hora": "6", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Miercoles"},
    //1101 - Jueves
    {"curso": "1101", "materia": "FIS", "hora": "1", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Jueves"},
    {"curso": "1101", "materia": "FIS", "hora": "2", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Jueves"},
    {"curso": "1101", "materia": "ARTIS", "hora": "3", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Jueves"},
    {"curso": "1101", "materia": "QUIM", "hora": "4", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Jueves"},
    {"curso": "1101", "materia": "QUIM", "hora": "5", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Jueves"},
    {"curso": "1101", "materia": "ETICA", "hora": "6", "salon": "S_3", "profesor": "Nancy Cobariza", "dia": "Jueves"},
    //1101 - Viernes
    {"curso": "1101", "materia": "SEMIO 2", "hora": "1", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Viernes"},
    {"curso": "1101", "materia": "SEMIO 2", "hora": "2", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Viernes"},
    {"curso": "1101", "materia": "FILO", "hora": "3", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Viernes"},
    {"curso": "1101", "materia": "FILO", "hora": "4", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Viernes"},
    {"curso": "1101", "materia": "TECNO", "hora": "5", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Viernes"},
    {"curso": "1101", "materia": "TECNO", "hora": "6", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Viernes"},
    
    //1102 - Lunes
    {"curso": "1102", "materia": "QUIM", "hora": "1", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Lunes"},
    {"curso": "1102", "materia": "QUIM", "hora": "2", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Lunes"},
    {"curso": "1102", "materia": "CALCULO", "hora": "3", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Lunes"},
    {"curso": "1102", "materia": "CALCULO", "hora": "4", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Lunes"},
    {"curso": "1102", "materia": "LCAS", "hora": "5", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Lunes"},
    {"curso": "1102", "materia": "LCAS", "hora": "6", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Lunes"},
    //1102 - Martes
    {"curso": "1102", "materia": "LO_MAT", "hora": "1", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Martes"},
    {"curso": "1102", "materia": "EDFIS", "hora": "2", "salon": "", "profesor": "Fabio Rozo", "dia": "Martes"},
    {"curso": "1102", "materia": "TECNO", "hora": "3", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Martes"},
    {"curso": "1102", "materia": "TECNO", "hora": "4", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Martes"},
    {"curso": "1102", "materia": "FILO", "hora": "5", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Martes"},
    {"curso": "1102", "materia": "FILO", "hora": "6", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Martes"},
    //1102 - Miercoles
    {"curso": "1102", "materia": "SEMIO 2", "hora": "1", "salon": "S_10", "profesor": "04-Soraya Fonseca", "dia": "Miercoles"},
    {"curso": "1102", "materia": "ETICA", "hora": "2", "salon": "S_5", "profesor": "Nancy Combariza", "dia": "Miercoles"},
    {"curso": "1102", "materia": "CPE", "hora": "3", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Miercoles"},
    {"curso": "1102", "materia": "CPE", "hora": "4", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Miercoles"},
    {"curso": "1102", "materia": "ING_Conv", "hora": "5", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Miercoles"},
    {"curso": "1102", "materia": "ING_Conv", "hora": "6", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Miercoles"},
    //1102 - Jueves
    {"curso": "1102", "materia": "ING_Bas", "hora": "1", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Jueves"},
    {"curso": "1102", "materia": "ING_Bas", "hora": "2", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Jueves"},
    {"curso": "1102", "materia": "RELIG", "hora": "3", "salon": "S_13", "profesor": "Edward Estupiñan", "dia": "Jueves"},
    {"curso": "1102", "materia": "EDFIS", "hora": "4", "salon": "", "profesor": "Fabio Rozo", "dia": "Jueves"},
    {"curso": "1102", "materia": "ARTIS", "hora": "5", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Jueves"},
    {"curso": "1102", "materia": "QUIM", "hora": "6", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Jueves"},
    //1102 - Viernes
    {"curso": "1102", "materia": "ING_Bas", "hora": "1", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Viernes"},
    {"curso": "1102", "materia": "ING_Bas", "hora": "2", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Viernes"},
    {"curso": "1102", "materia": "SEMIO 2", "hora": "3", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Viernes"},
    {"curso": "1102", "materia": "SEMIO 2", "hora": "4", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Viernes"},
    {"curso": "1102", "materia": "FIS", "hora": "5", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Viernes"},
    {"curso": "1102", "materia": "FIS", "hora": "6", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Viernes"},
    //1103 - Lunes
    {"curso": "1103", "materia": "FIS", "hora": "1", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Lunes"},
    {"curso": "1103", "materia": "FIS", "hora": "2", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Lunes"},
    {"curso": "1103", "materia": "SEMIO 2", "hora": "3", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Lunes"},
    {"curso": "1103", "materia": "SEMIO 2", "hora": "4", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Lunes"},
    {"curso": "1103", "materia": "EDFIS", "hora": "5", "salon": "", "profesor": "Fabio Rozo", "dia": "Lunes"},
    {"curso": "1103", "materia": "RELIG", "hora": "6", "salon": "S_1", "profesor": "Edward Estupiñan", "dia": "Lunes"},
    //1103 - Martes
    {"curso": "1103", "materia": "ING_Bas", "hora": "1", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Martes"},
    {"curso": "1103", "materia": "ING_Bas", "hora": "2", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Martes"},
    {"curso": "1103", "materia": "SEMIO 2", "hora": "3", "salon": "S_10", "profesor": "10-Aura Medina", "dia": "Martes"},
    {"curso": "1103", "materia": "ARTIS", "hora": "4", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Martes"},
    {"curso": "1103", "materia": "TECNO", "hora": "5", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Martes"},
    {"curso": "1103", "materia": "TECNO", "hora": "6", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Martes"},
    //1103 - Miercoles
    {"curso": "1103", "materia": "QUIM", "hora": "1", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Miercoles"},
    {"curso": "1103", "materia": "QUIM", "hora": "2", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Miercoles"},
    {"curso": "1103", "materia": "ING_Conv", "hora": "3", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Miercoles"},
    {"curso": "1103", "materia": "ING_Conv", "hora": "4", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Miercoles"},
    {"curso": "1103", "materia": "CALCULO", "hora": "5", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Miercoles"},
    {"curso": "1103", "materia": "CALCULO", "hora": "6", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Miercoles"},
    //1103 - Jueves
    {"curso": "1103", "materia": "QUIM", "hora": "1", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Jueves"},
    {"curso": "1103", "materia": "ETICA", "hora": "2", "salon": "S_4", "profesor": "Nancy Combariza", "dia": "Jueves"},
    {"curso": "1103", "materia": "CPE", "hora": "3", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Jueves"},
    {"curso": "1103", "materia": "CPE", "hora": "4", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Jueves"},
    {"curso": "1103", "materia": "EDFIS", "hora": "5", "salon": "", "profesor": "Fabio Rozo", "dia": "Jueves"},
    {"curso": "1103", "materia": "LO_MAT", "hora": "6", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Jueves"},
    //1103 - Viernes
    {"curso": "1103", "materia": "LCAS", "hora": "1", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Viernes"},
    {"curso": "1103", "materia": "LCAS", "hora": "2", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Viernes"},
    {"curso": "1103", "materia": "ING_Bas", "hora": "3", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Viernes"},
    {"curso": "1103", "materia": "ING_Bas", "hora": "4", "salon": "S_13", "profesor": "13-Adriana Saenz", "dia": "Viernes"},
    {"curso": "1103", "materia": "FILO", "hora": "5", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Viernes"},
    {"curso": "1103", "materia": "FILO", "hora": "6", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Viernes"},
    //1104 - Lunes
    {"curso": "1104", "materia": "EDFIS", "hora": "1", "salon": "", "profesor": "Fabio Rozo", "dia": "Lunes"},
    {"curso": "1104", "materia": "ARTIS", "hora": "2", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Lunes"},
    {"curso": "1104", "materia": "COMP_M", "hora": "3", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Lunes"},
    {"curso": "1104", "materia": "COMP_M", "hora": "4", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Lunes"},
    {"curso": "1104", "materia": "FILO", "hora": "5", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Lunes"},
    {"curso": "1104", "materia": "FILO", "hora": "6", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Lunes"},
    //1104 - Martes
    {"curso": "1104", "materia": "CPE", "hora": "1", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Martes"},
    {"curso": "1104", "materia": "CPE", "hora": "2", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Martes"},
    {"curso": "1104", "materia": "ING_Bas", "hora": "3", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Martes"},
    {"curso": "1104", "materia": "ING_Bas", "hora": "4", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Martes"},
    {"curso": "1104", "materia": "QUIM", "hora": "5", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Martes"},
    {"curso": "1104", "materia": "QUIM", "hora": "6", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Martes"},
    //1104 - Miercoles
    {"curso": "1104", "materia": "LO_MAT", "hora": "1", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Miercoles"},
    {"curso": "1104", "materia": "ESTADIS", "hora": "2", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Miercoles"},
    {"curso": "1104", "materia": "ESTADIS", "hora": "3", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Miercoles"},
    {"curso": "1104", "materia": "EDFIS", "hora": "4", "salon": "", "profesor": "Fabio Rozo", "dia": "Miercoles"},
    {"curso": "1104", "materia": "FIS", "hora": "5", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Miercoles"},
    {"curso": "1104", "materia": "FIS", "hora": "6", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Miercoles"},
    //1104 - Jueves
    {"curso": "1104", "materia": "TECNO", "hora": "1", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Jueves"},
    {"curso": "1104", "materia": "TECNO", "hora": "2", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Jueves"},
    {"curso": "1104", "materia": "QUIM", "hora": "3", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Jueves"},
    {"curso": "1104", "materia": "LCAS", "hora": "4", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Jueves"},
    {"curso": "1104", "materia": "LCAS", "hora": "5", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Jueves"},
    {"curso": "1104", "materia": "COMP_M", "hora": "6", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Jueves"},
    //1104 - Viernes
    {"curso": "1104", "materia": "CALCULO", "hora": "1", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Viernes"},
    {"curso": "1104", "materia": "CALCULO", "hora": "2", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Viernes"},
    {"curso": "1104", "materia": "ETICA", "hora": "3", "salon": "S_6", "profesor": "Nancy Combariza", "dia": "Viernes"},
    {"curso": "1104", "materia": "ING_Bas", "hora": "4", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Viernes"},
    {"curso": "1104", "materia": "ING_Bas", "hora": "5", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Viernes"},
    {"curso": "1104", "materia": "RELIG", "hora": "6", "salon": "S_1", "profesor": "Edward Estupiñan", "dia": "Viernes"},
    //1105 - Lunes
    {"curso": "1105", "materia": "FILO", "hora": "1", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Lunes"},
    {"curso": "1105", "materia": "FILO", "hora": "2", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Lunes"},
    {"curso": "1105", "materia": "FIS", "hora": "3", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Lunes"},
    {"curso": "1105", "materia": "FIS", "hora": "4", "salon": "L_FIS", "profesor": "LF-Marisol Barrera", "dia": "Lunes"},
    {"curso": "1105", "materia": "TECNO", "hora": "5", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Lunes"},
    {"curso": "1105", "materia": "TECNO", "hora": "6", "salon": "SALA_2", "profesor": "S2-Alba Leal", "dia": "Lunes"},
    //1105 - Martes
    {"curso": "1105", "materia": "QUIM", "hora": "1", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Martes"},
    {"curso": "1105", "materia": "QUIM", "hora": "2", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Martes"},
    {"curso": "1105", "materia": "LO_MAT", "hora": "3", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Martes"},
    {"curso": "1105", "materia": "RELIG", "hora": "4", "salon": "S_11", "profesor": "Edward Estupiñan", "dia": "Martes"},
    {"curso": "1105", "materia": "COMP_M", "hora": "5", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Martes"},
    {"curso": "1105", "materia": "EDFIS", "hora": "6", "salon": "", "profesor": "Fabio Rozo", "dia": "Martes"},
    //1105 - Miercoles
    {"curso": "1105", "materia": "LCAS", "hora": "1", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Miercoles"},
    {"curso": "1105", "materia": "LCAS", "hora": "2", "salon": "S_14", "profesor": "14-Gloria Robayo", "dia": "Miercoles"},
    {"curso": "1105", "materia": "CALCULO", "hora": "3", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Miercoles"},
    {"curso": "1105", "materia": "CALCULO", "hora": "4", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Miercoles"},
    {"curso": "1105", "materia": "QUIM", "hora": "5", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Miercoles"},
    {"curso": "1105", "materia": "ARTIS", "hora": "6", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Miercoles"},
    //1105 - Jueves
    {"curso": "1105", "materia": "COMP_M", "hora": "1", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Jueves"},
    {"curso": "1105", "materia": "COMP_M", "hora": "2", "salon": "S_5", "profesor": "05-Mercedez Martínez", "dia": "Jueves"},
    {"curso": "1105", "materia": "ING_Bas", "hora": "3", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Jueves"},
    {"curso": "1105", "materia": "ING_Bas", "hora": "4", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Jueves"},
    {"curso": "1105", "materia": "ESTADIS", "hora": "5", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Jueves"},
    {"curso": "1105", "materia": "ESTADIS", "hora": "6", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Jueves"},
    //1105 - Viernes
    {"curso": "1105", "materia": "ING_Bas", "hora": "1", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Viernes"},
    {"curso": "1105", "materia": "ING_Bas", "hora": "2", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Viernes"},
    {"curso": "1105", "materia": "CPE", "hora": "3", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Viernes"},
    {"curso": "1105", "materia": "CPE", "hora": "4", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Viernes"},
    {"curso": "1105", "materia": "EDFIS", "hora": "5", "salon": "", "profesor": "Fabio Rozo", "dia": "Viernes"},
        {"curso": "1105", "materia": "ETICA", "hora": "6", "salon": "S_6", "profesor": "Nancy Combariza", "dia": "Viernes"},
    //1106 - Lunes
    {"curso": "1106", "materia": "RELIG", "hora": "1", "salon": "S_11", "profesor": "Edward Estupiñan", "dia": "Lunes"},
    {"curso": "1106", "materia": "CPE", "hora": "2", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Lunes"},
    {"curso": "1106", "materia": "CPE", "hora": "3", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Lunes"},
    {"curso": "1106", "materia": "EDFIS", "hora": "4", "salon": "", "profesor": "Angela Morales", "dia": "Lunes"},
    {"curso": "1106", "materia": "ING_Bas", "hora": "5", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Lunes"},
    {"curso": "1106", "materia": "ING_Bas", "hora": "6", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Lunes"},
    //1106 - Martes
    {"curso": "1106", "materia": "TECNO", "hora": "1", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Martes"},
    {"curso": "1106", "materia": "TECNO", "hora": "2", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Martes"},
    {"curso": "1106", "materia": "LCAS", "hora": "3", "salon": "S_14", "profesor": "Esperanza Orozco", "dia": "Martes"},
    {"curso": "1106", "materia": "LCAS", "hora": "4", "salon": "S_14", "profesor": "Esperanza Orozco", "dia": "Martes"},
    {"curso": "1106", "materia": "BIOQUIM", "hora": "5", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Martes"},
    {"curso": "1106", "materia": "BIOQUIM", "hora": "6", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Martes"},
    //1106 - Miercoles
    {"curso": "1106", "materia": "QUIM", "hora": "1", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Miercoles"},
    {"curso": "1106", "materia": "FILO", "hora": "2", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Miercoles"},
    {"curso": "1106", "materia": "FILO", "hora": "3", "salon": "S_19", "profesor": "19-Vilma Navarro", "dia": "Miercoles"},
    {"curso": "1106", "materia": "ARTIS", "hora": "4", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Miercoles"},
    {"curso": "1106", "materia": "FIS", "hora": "5", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Miercoles"},
    {"curso": "1106", "materia": "FIS", "hora": "6", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Miercoles"},
    //1106 - Jueves
    {"curso": "1106", "materia": "ING_Bas", "hora": "1", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Jueves"},
    {"curso": "1106", "materia": "ING_Bas", "hora": "2", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Jueves"},
    {"curso": "1106", "materia": "ETICA", "hora": "3", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Jueves"},
    {"curso": "1106", "materia": "LO_MAT", "hora": "4", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Jueves"},
    {"curso": "1106", "materia": "QUIM", "hora": "5", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Jueves"},
    {"curso": "1106", "materia": "QUIM", "hora": "6", "salon": "S_11", "profesor": "11-Lilia Montoya", "dia": "Jueves"},
    //1106 - Viernes
    {"curso": "1106", "materia": "EDFIS", "hora": "1", "salon": "", "profesor": "Angela Morales", "dia": "Viernes"},
    {"curso": "1106", "materia": "BIOQUIM", "hora": "2", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Viernes"},
    {"curso": "1106", "materia": "CALCULO", "hora": "3", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Viernes"},
    {"curso": "1106", "materia": "CALCULO", "hora": "4", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Viernes"},
    {"curso": "1106", "materia": "Bio_MOL", "hora": "5", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Viernes"},
    {"curso": "1106", "materia": "Bio_MOL", "hora": "6", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Viernes"},
    //1107 - Lunes
    {"curso": "1107", "materia": "LCAS", "hora": "1", "salon": "S_14", "profesor": "Esperanza Orozco", "dia": "Lunes"},
    {"curso": "1107", "materia": "LCAS", "hora": "2", "salon": "S_14", "profesor": "Esperanza Orozco", "dia": "Lunes"},
    {"curso": "1107", "materia": "ING_Bas", "hora": "3", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Lunes"},
    {"curso": "1107", "materia": "ING_Bas", "hora": "4", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Lunes"},
    {"curso": "1107", "materia": "TECNO", "hora": "5", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Lunes"},
    {"curso": "1107", "materia": "TECNO", "hora": "6", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Lunes"},
    //1107 - Martes
    {"curso": "1107", "materia": "FILO", "hora": "1", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Martes"},
    {"curso": "1107", "materia": "FILO", "hora": "2", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Martes"},
    {"curso": "1107", "materia": "ARTIS", "hora": "3", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Martes"},
    {"curso": "1107", "materia": "LO_MAT", "hora": "4", "salon": "S_4", "profesor": "04-Soraya Fonseca", "dia": "Martes"},
    {"curso": "1107", "materia": "ING_Bas", "hora": "5", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Martes"},
    {"curso": "1107", "materia": "ING_Bas", "hora": "6", "salon": "S_12", "profesor": "12-Liliana Lizarazo", "dia": "Martes"},
    //1107 - Miercoles
    {"curso": "1107", "materia": "EDFIS", "hora": "1", "salon": "", "profesor": "Angela Morales", "dia": "Miercoles"},
    {"curso": "1107", "materia": "RELIG", "hora": "2", "salon": "S_13", "profesor": "Edward Estupiñan", "dia": "Miercoles"},
    {"curso": "1107", "materia": "Bio_MOL", "hora": "3", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Miercoles"},
    {"curso": "1107", "materia": "Bio_MOL", "hora": "4", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Miercoles"},
    {"curso": "1107", "materia": "BIOQUIM", "hora": "5", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Miercoles"},
    {"curso": "1107", "materia": "QUIM", "hora": "6", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Miercoles"},
    //1107 - Jueves
    {"curso": "1107", "materia": "CPE", "hora": "1", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Jueves"},
    {"curso": "1107", "materia": "CPE", "hora": "2", "salon": "S_17", "profesor": "17-Gloria Castro", "dia": "Jueves"},
    {"curso": "1107", "materia": "BIOQUIM", "hora": "3", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Jueves"},
    {"curso": "1107", "materia": "BIOQUIM", "hora": "4", "salon": "S_1", "profesor": "15-Yolima Alfaro", "dia": "Jueves"},
    {"curso": "1107", "materia": "CALCULO", "hora": "5", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Jueves"},
    {"curso": "1107", "materia": "CALCULO", "hora": "6", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Jueves"},
    //1107 - Viernes
    {"curso": "1107", "materia": "FIS", "hora": "1", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Viernes"},
    {"curso": "1107", "materia": "FIS", "hora": "2", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Viernes"},
    {"curso": "1107", "materia": "QUIM", "hora": "3", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Viernes"},
    {"curso": "1107", "materia": "QUIM", "hora": "4", "salon": "S_21", "profesor": "21-Angelica Conde", "dia": "Viernes"},
    {"curso": "1107", "materia": "ETICA", "hora": "5", "salon": "S_6", "profesor": "Nancy Combariza", "dia": "Viernes"},
    {"curso": "1107", "materia": "EDFIS", "hora": "6", "salon": "", "profesor": "Angela Morales", "dia": "Viernes"},
    //1108 - Lunes
    {"curso": "1108", "materia": "LO_MAT", "hora": "1", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Lunes"},
    {"curso": "1108", "materia": "TECNO", "hora": "2", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Lunes"},
    {"curso": "1108", "materia": "TECNO", "hora": "3", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Lunes"},
    {"curso": "1108", "materia": "QUIM", "hora": "4", "salon": "S_16", "profesor": "16-William Pita", "dia": "Lunes"},
    {"curso": "1108", "materia": "ING_Bas", "hora": "5", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Lunes"},
    {"curso": "1108", "materia": "ING_Bas", "hora": "6", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Lunes"},
    //1108 - Martes
    {"curso": "1108", "materia": "FIS", "hora": "1", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Martes"},
    {"curso": "1108", "materia": "FIS", "hora": "2", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Martes"},
    {"curso": "1108", "materia": "LCAS", "hora": "3", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Martes"},
    {"curso": "1108", "materia": "EDFIS", "hora": "4", "salon": "", "profesor": "Angela Morales", "dia": "Martes"},
    {"curso": "1108", "materia": "CPE", "hora": "5", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Martes"},
    {"curso": "1108", "materia": "CPE", "hora": "6", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Martes"},
    //1108 - Miercoles
    {"curso": "1108", "materia": "QUIM", "hora": "1", "salon": "S_16", "profesor": "16-William Pita", "dia": "Miercoles"},
    {"curso": "1108", "materia": "QUIM", "hora": "2", "salon": "S_16", "profesor": "16-William Pita", "dia": "Miercoles"},
    {"curso": "1108", "materia": "FILO", "hora": "3", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Miercoles"},
    {"curso": "1108", "materia": "FILO", "hora": "4", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Miercoles"},
    {"curso": "1108", "materia": "LCAS", "hora": "5", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Miercoles"},
    {"curso": "1108", "materia": "LCAS", "hora": "6", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Miercoles"},
    //1108 - Jueves
    {"curso": "1108", "materia": "APLIC 2", "hora": "1", "salon": "SALA_5", "profesor": "S5-Rosa Guerrero", "dia": "Jueves"},
    {"curso": "1108", "materia": "APLIC 2", "hora": "2", "salon": "SALA_5", "profesor": "S5-Rosa Guerrero", "dia": "Jueves"},
    {"curso": "1108", "materia": "CALCULO", "hora": "3", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Jueves"},
    {"curso": "1108", "materia": "CPE", "hora": "4", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Jueves"},
    {"curso": "1108", "materia": "EDFIS", "hora": "5", "salon": "", "profesor": "Angela Morales", "dia": "Jueves"},
    {"curso": "1108", "materia": "ARTIS", "hora": "6", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Jueves"},
    //1108 - Viernes
    {"curso": "1108", "materia": "RELIG", "hora": "1", "salon": "S_16", "profesor": "Edward Estupiñan", "dia": "Viernes"},
    {"curso": "1108", "materia": "ETICA", "hora": "2", "salon": "S_5", "profesor": "Nancy Combariza", "dia": "Viernes"},
    {"curso": "1108", "materia": "ING_Bas", "hora": "3", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Viernes"},
    {"curso": "1108", "materia": "ING_Bas", "hora": "4", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Viernes"},
    {"curso": "1108", "materia": "CALCULO", "hora": "5", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Viernes"},
    {"curso": "1108", "materia": "CALCULO", "hora": "6", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Viernes"},
    //1109 - Lunes
    {"curso": "1109", "materia": "LCAS", "hora": "1", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Lunes"},
    {"curso": "1109", "materia": "QUIM", "hora": "2", "salon": "S_16", "profesor": "16-William Pita", "dia": "Lunes"},
    {"curso": "1109", "materia": "EDFIS", "hora": "3", "salon": "", "profesor": "Angela Morales", "dia": "Lunes"},
    {"curso": "1109", "materia": "ARTIS", "hora": "4", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Lunes"},
    {"curso": "1109", "materia": "CALCULO", "hora": "5", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Lunes"},
    {"curso": "1109", "materia": "CALCULO", "hora": "6", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Lunes"},
    //1109 - Martes
    {"curso": "1109", "materia": "CPE", "hora": "1", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Martes"},
    {"curso": "1109", "materia": "CPE", "hora": "2", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Martes"},
    {"curso": "1109", "materia": "FIS", "hora": "3", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Martes"},
    {"curso": "1109", "materia": "FIS", "hora": "4", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Martes"},
    {"curso": "1109", "materia": "ING_Bas", "hora": "5", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Martes"},
    {"curso": "1109", "materia": "ING_Bas", "hora": "6", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Martes"},
    //1109 - Miercoles
    {"curso": "1109", "materia": "ING_Bas", "hora": "1", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Miercoles"},
    {"curso": "1109", "materia": "ING_Bas", "hora": "2", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Miercoles"},
    {"curso": "1109", "materia": "QUIM", "hora": "3", "salon": "S_16", "profesor": "16-William Pita", "dia": "Miercoles"},
    {"curso": "1109", "materia": "QUIM", "hora": "4", "salon": "S_16", "profesor": "16-William Pita", "dia": "Miercoles"},
    {"curso": "1109", "materia": "FILO", "hora": "5", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Miercoles"},
    {"curso": "1109", "materia": "FILO", "hora": "6", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Miercoles"},
    //1109 - Jueves
    {"curso": "1109", "materia": "RELIG", "hora": "1", "salon": "S_16", "profesor": "Edward Estupiñan", "dia": "Jueves"},
    {"curso": "1109", "materia": "LO_MAT", "hora": "2", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Jueves"},
    {"curso": "1109", "materia": "TECNO", "hora": "3", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Jueves"},
    {"curso": "1109", "materia": "TECNO", "hora": "4", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Jueves"},
    {"curso": "1109", "materia": "APLIC 2", "hora": "5", "salon": "SALA_8", "profesor": "S6-Yadith Mesa", "dia": "Jueves"},
    {"curso": "1109", "materia": "APLIC 2", "hora": "6", "salon": "SALA_8", "profesor": "S6-Yadith Mesa", "dia": "Jueves"},
    //1109 - Viernes
    {"curso": "1109", "materia": "ETICA", "hora": "1", "salon": "S_5", "profesor": "Nancy Combariza", "dia": "Viernes"},
    {"curso": "1109", "materia": "CALCULO", "hora": "2", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Viernes"},
    {"curso": "1109", "materia": "EDFIS", "hora": "3", "salon": "", "profesor": "Angela Morales", "dia": "Viernes"},
    {"curso": "1109", "materia": "CPE", "hora": "4", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Viernes"},
    {"curso": "1109", "materia": "LCAS", "hora": "5", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Viernes"},
    {"curso": "1109", "materia": "LCAS", "hora": "6", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Viernes"},





    //1110 - Lunes
    {"curso": "1110", "materia": "EDFIS", "hora": "1", "salon": "", "profesor": "Angela Morales", "dia": "Lunes"},
    {"curso": "1110", "materia": "LO_MAT", "hora": "2", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Lunes"},
    {"curso": "1110", "materia": "CPE", "hora": "3", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Lunes"},
    {"curso": "1110", "materia": "CPE", "hora": "4", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Lunes"},
    {"curso": "1110", "materia": "QUIM", "hora": "5", "salon": "S_16", "profesor": "16-William Pita", "dia": "Lunes"},
    {"curso": "1110", "materia": "QUIM", "hora": "6", "salon": "S_16", "profesor": "16-William Pita", "dia": "Lunes"},

    //1110 - Martes
    {"curso": "1110", "materia": "ING_Bas", "hora": "1", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Martes"},
    {"curso": "1110", "materia": "ING_Bas", "hora": "2", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Martes"},
    {"curso": "1110", "materia": "CALCULO", "hora": "3", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Martes"},
    {"curso": "1110", "materia": "CALCULO", "hora": "4", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Martes"},
    {"curso": "1110", "materia": "FILO", "hora": "5", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Martes"},
    {"curso": "1110", "materia": "FILO", "hora": "6", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Martes"},

    //1110 - Miercoles
    {"curso": "1110", "materia": "RELIG", "hora": "1", "salon": "S_13", "profesor": "Edward Estupiñan", "dia": "Miercoles"},
    {"curso": "1110", "materia": "ARTIS", "hora": "2", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Miercoles"},
    {"curso": "1110", "materia": "EDFIS", "hora": "3", "salon": "", "profesor": "Angela Morales", "dia": "Miercoles"},
    {"curso": "1110", "materia": "FINANZAS", "hora": "4", "salon": "SALA_6", "profesor": "S6-Katherine Sepúlveda", "dia": "Miercoles"},
    {"curso": "1110", "materia": "FINANZAS", "hora": "5", "salon": "SALA_6", "profesor": "S6-Katherine Sepúlveda", "dia": "Miercoles"},
    {"curso": "1110", "materia": "CALCULO", "hora": "6", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Miercoles"},

    //1110 - Jueves
    {"curso": "1110", "materia": "LCAS", "hora": "1", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Jueves"},
    {"curso": "1110", "materia": "LCAS", "hora": "2", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Jueves"},
    {"curso": "1110", "materia": "FIS", "hora": "3", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Jueves"},
    {"curso": "1110", "materia": "FIS", "hora": "4", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Jueves"},
    {"curso": "1110", "materia": "ING_Bas", "hora": "5", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Jueves"},
    {"curso": "1110", "materia": "ING_Bas", "hora": "6", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Jueves"},

    //1110 - Viernes
    {"curso": "1110", "materia": "LCAS", "hora": "1", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Viernes"},
    {"curso": "1110", "materia": "TECNO", "hora": "2", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Viernes"},
    {"curso": "1110", "materia": "TECNO", "hora": "3", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Viernes"},
    {"curso": "1110", "materia": "QUIM", "hora": "4", "salon": "S_16", "profesor": "16-William Pita", "dia": "Viernes"},
    {"curso": "1110", "materia": "CPE", "hora": "5", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Viernes"},
    {"curso": "1110", "materia": "ETICA", "hora": "6", "salon": "S_1", "profesor": "06-Katherine Sepúlveda", "dia": "Viernes"},




    
    //1111 - Lunes
    {"curso": "1111", "materia": "CALCULO", "hora": "1", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Lunes"},
    {"curso": "1111", "materia": "CPE", "hora": "2", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Lunes"},
    {"curso": "1111", "materia": "ING_Bas", "hora": "3", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Lunes"},
    {"curso": "1111", "materia": "ING_Bas", "hora": "4", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Lunes"},
    {"curso": "1111", "materia": "LCAS", "hora": "5", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Lunes"},
    {"curso": "1111", "materia": "LCAS", "hora": "6", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Lunes"},

    //1111 - Martes
    {"curso": "1111", "materia": "RELIG", "hora": "1", "salon": "S_12", "profesor": "Edward Estupiñan", "dia": "Martes"},
    {"curso": "1111", "materia": "LO_MAT", "hora": "2", "salon": "S_6", "profesor": "06-Martín Rojas", "dia": "Martes"},
    {"curso": "1111", "materia": "QUIM", "hora": "3", "salon": "S_16", "profesor": "16-William Pita", "dia": "Martes"},
    {"curso": "1111", "materia": "QUIM", "hora": "4", "salon": "S_16", "profesor": "16-William Pita", "dia": "Martes"},
    {"curso": "1111", "materia": "TECNO", "hora": "5", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Martes"},
    {"curso": "1111", "materia": "TECNO", "hora": "6", "salon": "SALA_5", "profesor": "S5-Raúl Barón", "dia": "Martes"},

    //1111 - Miercoles
    {"curso": "1111", "materia": "FILO", "hora": "1", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Miercoles"},
    {"curso": "1111", "materia": "FILO", "hora": "2", "salon": "S_20", "profesor": "20-Victor Maldonado", "dia": "Miercoles"},
    {"curso": "1111", "materia": "ING_Bas", "hora": "3", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Miercoles"},
    {"curso": "1111", "materia": "ING_Bas", "hora": "4", "salon": "S_8", "profesor": "08-Lorena Rojas", "dia": "Miercoles"},
    {"curso": "1111", "materia": "ARTIS", "hora": "5", "salon": "S_15", "profesor": "15-Edelmira Carvajal", "dia": "Miercoles"},
    {"curso": "1111", "materia": "EDFIS", "hora": "6", "salon": "", "profesor": "Angela Morales", "dia": "Miercoles"},

    //1111 - Jueves
    {"curso": "1111", "materia": "CALCULO", "hora": "1", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Jueves"},
    {"curso": "1111", "materia": "CALCULO", "hora": "2", "salon": "S_7", "profesor": "07-Dario Meza", "dia": "Jueves"},
    {"curso": "1111", "materia": "FINANZAS", "hora": "3", "salon": "SALA_6", "profesor": "S6-Katherine Sepúlveda", "dia": "Jueves"},
    {"curso": "1111", "materia": "FINANZAS", "hora": "4", "salon": "SALA_6", "profesor": "S6-Katherine Sepúlveda", "dia": "Jueves"},
    {"curso": "1111", "materia": "FIS", "hora": "5", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Jueves"},
    {"curso": "1111", "materia": "FIS", "hora": "6", "salon": "S_2", "profesor": "02-Henry Moreno", "dia": "Jueves"},

    //1111 - Viernes
    {"curso": "1111", "materia": "CPE", "hora": "1", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Viernes"},
    {"curso": "1111", "materia": "CPE", "hora": "2", "salon": "S_9", "profesor": "09-Jeffer Bohórquez", "dia": "Viernes"},
    {"curso": "1111", "materia": "LCAS", "hora": "3", "salon": "S_3", "profesor": "03-Yhon Pava", "dia": "Viernes"},
    {"curso": "1111", "materia": "EDFIS", "hora": "4", "salon": "", "profesor": "Angela Morales", "dia": "Viernes"},
    {"curso": "1111", "materia": "ETICA", "hora": "5", "salon": "S_1", "profesor": "06-Katherine Sepúlveda", "dia": "Viernes"},
    {"curso": "1111", "materia": "QUIM", "hora": "6", "salon": "S_16", "profesor": "16-William Pita", "dia": "Viernes"},
];